baseurl = "mattsblog.netlify.com/"
title = "Matt's Blog"
theme = "academic"
copyright = "&copy; 2018"
[languages.en]
  languageCode = "en-us"
paginate = 10
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true

disqusShortname = ""
googleAnalytics = ""


defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).
  extensions = ["backslashLineBreak"]

[params]
  name = "Matthew"
  role = "Tech Lover"

  # Organizations/Affiliations.
  #   Separate multiple entries with a comma, using the form: `[ {name="Org1", url=""}, {name="Org2", url=""} ]`.
  organizations = [ { name = "Stanford University", url = "" } ]

  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "portrait.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.

  email = "test@example.org"
  address = "Building 1 Room 1, Stanford University, California, 90210, USA"
  office_hours = """
  Monday 10:00 to 13:00\\
  Wednesday 09:00 to 10:00\\
  Otherwise email to book an appointment
  """
  phone = "888 888 88 88"
  skype = "echo123"
  telegram = ""
  keybase = ""  # Your keybase.io username.

  map = 0
  map_api_key = ""
  latitude = "37.4275"
  longitude = "-122.1697"
  zoom = 15

  color_theme = "default"

  day_night = true
  
  font = "default"

  description = ""

  sharing_image = ""

	Twitter.
  twitter = ""


  logo = ""

  date_format = "Jan 2, 2006"

  time_format = "3:04 PM"

  reading_time = true

  comment_count = true

  section_pager = false

  math = false

writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = []
  # highlight_style = "github"

  sharing = true

  privacy_pack = false

  custom_css = []
  custom_js  = []

  publication_types = [
    'Uncategorized',  # 0
    'Conference paper',  # 1
    'Journal article',  # 2
    'Manuscript',  # 3
    'Report',  # 4
    'Book',  # 5
    'Book section'  # 6
  ]

  [params.talks]
    # Show talk time?
    time = true

  [params.publications]
    # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "January, 2006"

  [params.projects]
    # List publications and talks related to the project?
    list_children = true

    # Post list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = Stream
    post_format = 2

    # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    #   4 = Stream
    publication_format = 4

    # Talk list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = Stream
    talk_format = 2

  # Social/Academic Networking
  #
  # Icon pack "fab" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fas" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fontawesome.com/icons
  #
  # Icon pack "ai" includes the following academic icons:
  #
  #   cv, google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fas"
    link = "#contact"  # For a direct email link, use "mailto:test@example.org".

  [[params.social]]
    icon = "twitter"
    icon_pack = "fab"
    link = "https://twitter.com/GeorgeCushen"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ"

  [[params.social]]
    icon = "github"
    icon_pack = "fab"
    link = "https://github.com/gcushen"

[params.menus]
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Tutorials"
  url = "/tutorial/"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[menu.main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 7

# Search.
[params.search]
  # Search provider:
  #   0: No search engine
  #   1: Built-in (Fuse)
  #   2: Algolia (https://www.algolia.com)
  engine = 1

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [params.search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

[languages.en]
  languageCode = "en-us"

# Uncomment the lines below to configure your website in a second language.
#[languages.zh]
#  languageCode = "zh-Hans"
#  title = "Chinese website title..."
#  [languages.zh.params]
#    name = "Your name in Chinese..."
#    role = "Your role in Chinese..."
#  [[languages.zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
