---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections: 
upload_dir: static/img
public_path: "/public"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  output_directory: build
version: '0.52'
